package instructions;

public enum AddressingMode {
	IMPLICIT, ACCUMULATOR, IMMEDIATE, ZEROPAGE, ZEROPAGE_X, ZEROPAGE_Y, RELATIVE, ABSOLUTE, ABSOLUTE_X, ABSOLUTE_Y,
	INDIRECT, INDIRECT_X, INDIRECT_Y;
}